### ISSUE TITLE
Transition harrisonai/terraform from docker hub to Github container registry

### ISSUE THREAD

**Issue by comozo** [harrison-ai/cobalt-docker-terraform#9]
Related to https://github.com/harrison-ai/platform/issues/132
```[tasklist]
### Tasks
- [x] Update CI to publish to Github container registry instead.
- [x] Have team leads make the package public.
- [ ] Update downstream if able and/or communicate to stakeholders that Github path will get latest changes from here on.
- [x] Archive dockerhub repo (create backlog issue to do it in 1-2 months time).
```

Downstream repo to be updated

```[tasklist]
### Tasks
- [ ] hai-infra-jv
- [ ] hai-clip
- [ ] hai-ml
- [ ] hai-chexpert
```

**Comment by comozo** [comment]
For some reason I can't add the label infra and tech debt and bau @dcarrion87

**Comment by dcarrion87** [comment]
@comozo created and added.

**Comment by comozo** [comment]
@dcarrion87  Thank you. Just realised I have to create them at the repo level.

**Comment by comozo** [comment]
So far Jane seem to be the only one external stakeholder for this image.

**Comment by comozo** [comment]
Link to the task to archive the Docker Hub Repo https://github.com/harrison-ai/cobalt-docker-terraform/issues/11#issue-1654631350

**Comment by dcarrion87** [comment]
This issue has been migrated to Jira: https://harrison-ai.atlassian.net/browse/HPI-73
